/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_1521221051_feyzanursaka_odev2;

import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Feyza Nur Saka
 */
public class YoneticiEkrani extends javax.swing.JFrame {

    DefaultTableModel dtmmusterilistesi = new DefaultTableModel();
    DefaultTableModel dtmurunlistesi = new DefaultTableModel();

    /**
     * Creates new form YoneticiEkrani
     */
    public YoneticiEkrani() {
        initComponents();
        checkbox.setSelected(false);
        jbtn_musteriEkle.setEnabled(false);
        jbtn_musteriSil.setEnabled(false);
        String[] kolonIsimleri = {"MÜŞTERİ ID", "MÜSTERİ ADI", "MÜŞTERİ SOYADI"};
        String[] kolonIsimleri1 = {"KAYIT ID", "MÜŞTERİ ID", "TÜRÜ", "DURUM", "TARİH", "ÜCRET"};
        dtmmusterilistesi.setColumnIdentifiers(kolonIsimleri);
        dtmurunlistesi.setColumnIdentifiers(kolonIsimleri1);
        jtablemusterilistesi.setModel(dtmmusterilistesi);
        jtableurunlistesi.setModel(dtmurunlistesi);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select d from Musteri d");

        List<Musteri> musteriler = q.getResultList();
        for (Musteri m : musteriler) {
            jComboBoxmusteriid.addItem(m.getMusteriid());
            this.dtmmusterilistesi.addRow(new Object[]{m.getMusteriid(), m.getMusteriadi(), m.getMusterisoyadi()});
        }

        em.close();
        emf.close();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_musteriAdi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxt_musteriSoyadi = new javax.swing.JTextField();
        jbtn_musteriEkle = new javax.swing.JButton();
        jbtn_musteriSil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablemusterilistesi = new javax.swing.JTable();
        checkbox = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboCihazTuru = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtxt_TeslimTarihi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboCihazDurumu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxt_Ucret = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableurunlistesi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBoxmusteriid = new javax.swing.JComboBox<>();
        jCheckBox_onay1 = new javax.swing.JCheckBox();
        dosyayaat = new javax.swing.JButton();

        jScrollPane3.setViewportView(jScrollPane4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 354));

        jLabel5.setText("Adı :");

        jLabel6.setText("Soyadı :");

        jbtn_musteriEkle.setText("Müşteri Ekle");
        jbtn_musteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_musteriEkleActionPerformed(evt);
            }
        });

        jbtn_musteriSil.setText("Müşteri Sil");
        jbtn_musteriSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_musteriSilActionPerformed(evt);
            }
        });

        jtablemusterilistesi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablemusterilistesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablemusterilistesiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablemusterilistesi);

        checkbox.setText("Boşlukları Doldurdum.");
        checkbox.setVerifyInputWhenFocusTarget(false);
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });

        jButton5.setText("ÇIKIŞ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_musteriAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jtxt_musteriSoyadi, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_musteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_musteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_musteriAdi)
                    .addComponent(jbtn_musteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_musteriSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jbtn_musteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        jTabbedPane1.addTab("Müşteri İşlemleri", jPanel1);

        jLabel7.setText("Teslim Tarihi");

        jButton2.setText("Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboCihazTuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telefon", "Laptop", "" }));
        jComboCihazTuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCihazTuruActionPerformed(evt);
            }
        });

        jLabel1.setText("Müşteri Id ");

        jLabel2.setText("Cihaz Türü");

        jComboCihazDurumu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Onarıldı", "Beklemede", "Onarılmadı" }));

        jLabel8.setText("Ücret");

        jLabel4.setText("Cihaz Durumu");

        jtableurunlistesi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableurunlistesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableurunlistesiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtableurunlistesi);

        jButton1.setText("Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBoxmusteriid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxmusteriidİtemStateChanged(evt);
            }
        });

        jCheckBox_onay1.setText("Bilgileri Eksiksiz Doldurdum");
        jCheckBox_onay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_onay1ActionPerformed(evt);
            }
        });

        dosyayaat.setText("MÜŞTERİ BİLGİLERİNİ DOSYAYA AT");
        dosyayaat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyayaatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox_onay1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_Ucret, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_TeslimTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboCihazTuru, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboCihazDurumu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxmusteriid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dosyayaat))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dosyayaat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxmusteriid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCihazTuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboCihazDurumu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jtxt_TeslimTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_Ucret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addComponent(jCheckBox_onay1)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ürün İşlemleri", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed

        if (checkbox.isSelected()) {
            if (jtxt_musteriAdi.getText().length() == 0 || jtxt_musteriSoyadi.getText().length() == 0) {
                jbtn_musteriEkle.setEnabled(false);

                JOptionPane.showMessageDialog(rootPane, "Bilgilerinizi eksiksiz doldurun!");
                checkbox.setSelected(false);
            } else {
                jbtn_musteriEkle.setEnabled(true);
            }
        } else {
            jbtn_musteriEkle.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void jtablemusterilistesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablemusterilistesiMouseClicked
        // TODO add your handling code here:

        jbtn_musteriSil.setEnabled(true);
        return;

    }//GEN-LAST:event_jtablemusterilistesiMouseClicked

    private void jbtn_musteriSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_musteriSilActionPerformed
        // TODO add your handling code here:
        if (jtablemusterilistesi.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Silceğiniz Müşteriyi Seçiniz!");
            return;
        }
        String id = String.valueOf(jtablemusterilistesi.getValueAt(jtablemusterilistesi.getSelectedRow(), 0));
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();
        
        dtmmusterilistesi.removeRow(jtablemusterilistesi.getSelectedRow());
        
        
        Query q = em.createQuery("DELETE FROM Musteri m  WHERE m.musteriid=:id");
        Query q2 = em.createQuery("DELETE FROM Kayit k  WHERE k.musteriid=:id");

        q2.setParameter("id", Integer.parseInt(id));
        jComboBoxmusteriid.removeItem(Integer.parseInt(id));
        q.setParameter("id", Integer.parseInt(id));

        em.getTransaction().begin();
        q.executeUpdate();
        q2.executeUpdate();
        em.getTransaction().commit();
        em.close();
        emf.close();
        JOptionPane.showMessageDialog(rootPane, "Silme İşlemi Başarılı!");
        temizle();
        checkbox.setSelected(false);

    }//GEN-LAST:event_jbtn_musteriSilActionPerformed
    void temizle() {
        jtxt_musteriAdi.setText("");
        jtxt_musteriSoyadi.setText("");
    }
    private void jbtn_musteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_musteriEkleActionPerformed
       
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();
        if (!jtxt_musteriAdi.getText().trim().equals("") && !jtxt_musteriSoyadi.getText().trim().equals("")) {

            Query q = em.createQuery("SELECT m from Musteri m");
            Query q2 = em.createQuery("SELECT m from Yonetici m");
            List<Musteri> musteriler = q.getResultList();
            List<Yonetici> yoneticiler=q2.getResultList();
            
            
            int maxid = 0;
            for (Musteri mus : musteriler) {
                if (mus.getMusteriid() > maxid) {
                    maxid = mus.getMusteriid();
                }
            }

            Musteri m = new Musteri();
            em.getTransaction().begin();
        
//            m.setYoneticiid(YoneticiGirisEkrani.y_logined.getYoneticiid());
          
            m.setMusteriadi(jtxt_musteriAdi.getText());
            m.setMusterisoyadi(jtxt_musteriSoyadi.getText());
            m.setMusteriid(maxid + 1);
            Random rdm = new Random();
            m.setMusterisifre(String.valueOf(rdm.nextInt(9999) + 1000));
            

            this.dtmmusterilistesi.addRow(new Object[]{m.getMusteriid(), m.getMusteriadi(), m.getMusterisoyadi()});
            jComboBoxmusteriid.addItem(m.getMusteriid());

            JOptionPane.showMessageDialog(rootPane, "Kayıt Başarılı. " + m.getMusteriadi() + " " + m.getMusterisoyadi() + " için belirlenen şifre " + m.getMusterisifre());
            em.persist(m);
            em.getTransaction().commit();
            em.close();
            emf.close();

            temizle();
            checkbox.setSelected(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Boşlukları Doldurunuz!");
            jbtn_musteriEkle.setEnabled(false);
            jbtn_musteriSil.setEnabled(false);

        }
    }//GEN-LAST:event_jbtn_musteriEkleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String id = String.valueOf(jtableurunlistesi.getValueAt(jtableurunlistesi.getSelectedRow(), 1));
       
            if (jtablemusterilistesi.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Silceğiniz Kaydı Seçiniz!");
            return;
        }
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();

        
        Query q = em.createQuery("delete from Kayit k where k.kayitid=:kkayitid");
        q.setParameter("kkayitid", Integer.parseInt(id));
        em.getTransaction().begin();
        q.executeUpdate();
      
        em.getTransaction().commit();
     
        em.close();
        emf.close();
        ((DefaultTableModel) jtableurunlistesi.getModel()).removeRow(jtableurunlistesi.getSelectedRow());
        JOptionPane.showMessageDialog(rootPane, "Silme işlemi başarılı");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jtableurunlistesi.getModel();
        String[] kolonIsimleri1 = {"KAYIT ID", "MÜŞTERİ ID", "TÜRÜ", "DURUM", "TARİH", "ÜCRET"};
        String id = String.valueOf(jtableurunlistesi.getValueAt(jtableurunlistesi.getSelectedRow(), 0));
        if (jtableurunlistesi.getSelectedRow() == -1) {
            return;
        }
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("UPDATE Kayit k SET k.cihazdurumu=:durum, k.cihazturu=:tur, k.teslimtariihi=:tarih, k.ucret=:ucret WHERE k.kayitid=:id");
        q.setParameter("durum", jComboCihazDurumu.getSelectedItem() + "");
        q.setParameter("tur", jComboCihazTuru.getSelectedItem() + "");
        q.setParameter("tarih", jtxt_TeslimTarihi.getText());
        try {
            q.setParameter("ucret", Integer.parseInt(jtxt_Ucret.getText()));
            q.setParameter("id", Integer.parseInt(id));
            em.getTransaction().begin();
            q.executeUpdate();
            em.getTransaction().commit();
            
            if (jtableurunlistesi.getSelectedRow() != -1) {

            dtm.setValueAt(jComboBoxmusteriid.getSelectedItem(), jtableurunlistesi.getSelectedRow(), 1);
            dtm.setValueAt(jComboCihazTuru.getSelectedItem(), jtableurunlistesi.getSelectedRow(), 2);
            dtm.setValueAt(jComboCihazDurumu.getSelectedItem(), jtableurunlistesi.getSelectedRow(), 3);
            dtm.setValueAt(jtxt_TeslimTarihi.getText(), jtableurunlistesi.getSelectedRow(), 4);
            dtm.setValueAt(jtxt_Ucret.getText(), jtableurunlistesi.getSelectedRow(), 5);

            JOptionPane.showMessageDialog(rootPane, "Güncelleme başarılı.", "", ICONIFIED);

        } else {
            JOptionPane.showMessageDialog(rootPane, "değiştirceğiniz bilgiyi seçiniz", "", ICONIFIED);
        }
        

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Bilgileri Kontrol Ediniz!");
        }
       
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboCihazTuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCihazTuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCihazTuruActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
            EntityManager em = emf.createEntityManager();

            Query q = em.createQuery("SELECT k from Kayit k");
            List<Kayit> kayitlar = q.getResultList();
            int maxid = 0;
            for (Kayit kay : kayitlar) {
                if (kay.getKayitid() > maxid) {
                    maxid = kay.getKayitid();
                }
            }

            Kayit k = new Kayit();
            k.setMusteriid(Integer.parseInt("" + jComboBoxmusteriid.getSelectedItem()));
            k.setCihazdurumu("" + jComboCihazDurumu.getSelectedItem());
            k.setCihazturu("" + jComboCihazTuru.getSelectedItem());
            k.setTeslimtariihi(jtxt_TeslimTarihi.getText());
            k.setUcret(Integer.parseInt("" + jtxt_Ucret.getText()));
            k.setKayitid(maxid + 1);

            em.getTransaction().begin();
            em.persist(k);
            em.getTransaction().commit();

            Query q2 = em.createQuery("select k from Kayit k where k.musteriid=:mmusteriid");
            q2.setParameter("mmusteriid", Integer.parseInt("" + jComboBoxmusteriid.getSelectedItem()));
            List<Kayit> kayitlar2 = q2.getResultList();
            
            
            DefaultTableModel dtmk = new DefaultTableModel();
            dtmk.setColumnIdentifiers(new String[]{"MÜŞTERİ ID", "KAYIT ID", "TÜRÜ", "DURMU", "TARİH", "ÜCRET"});
            for (Kayit ka : kayitlar2) {

                dtmk.addRow(new Object[]{ka.getMusteriid(), ka.getKayitid(), ka.getCihazturu(), ka.getCihazdurumu(), ka.getTeslimtariihi(), ka.getUcret()});
            }
            em.close();
            emf.close();
            jButton1.setEnabled(true);
            jButton3.setEnabled(true);

            jtableurunlistesi.setModel(dtmk);

            JOptionPane.showMessageDialog(rootPane, "Kayıt Başarılı!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Bilgileri Kontrol Ediniz!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        GirisEkrani newyoneticigirisekrani = new GirisEkrani();
        newyoneticigirisekrani.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox_onay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_onay1ActionPerformed
        // TODO add your handling code here:

        if (jCheckBox_onay1.isSelected()) {
            if (jtxt_TeslimTarihi.getText().length() == 0 || jtxt_Ucret.getText().length() == 0) {
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                JOptionPane.showMessageDialog(rootPane, "Boş alan bırakmayın!");
                jCheckBox_onay1.setSelected(false);
            } else {
                jButton2.setEnabled(true);

            }
        } else {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox_onay1ActionPerformed

    private void jComboBoxmusteriidİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxmusteriidİtemStateChanged
        // TODO add your handling code here:
        if (jComboBoxmusteriid.getSelectedIndex() == -1) {
            return;
        }
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kayit k where k.musteriid=:mmusteriid");
        q.setParameter("mmusteriid", Integer.parseInt("" + jComboBoxmusteriid.getSelectedItem()));
        List<Kayit> kayitlar = q.getResultList();
        DefaultTableModel dtmk = new DefaultTableModel();
        dtmk.setColumnIdentifiers(new String[]{"MÜŞTERİ ID", "KAYIT ID", "TÜRÜ", "DURMU", "TARİH", "ÜCRET"});
        for (Kayit k : kayitlar) {

            dtmk.addRow(new Object[]{k.getMusteriid(), k.getKayitid(), k.getCihazturu(), k.getCihazdurumu(), k.getTeslimtariihi(), k.getUcret()});
        }
        jtableurunlistesi.setModel(dtmk);
        em.close();
        emf.close();


    }//GEN-LAST:event_jComboBoxmusteriidİtemStateChanged

    private void jtableurunlistesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableurunlistesiMouseClicked
        // TODO add your handling code here:

        jButton3.setEnabled(true);

        jButton1.setEnabled(true);

    }//GEN-LAST:event_jtableurunlistesiMouseClicked

    private void dosyayaatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyayaatActionPerformed
        ObjectOutputStream oos = null;
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();
        String dosya=("c:\\dosyalar\\MusteriListesi.txt");
         Query q = em.createQuery("SELECT m from Musteri m");
            List<Musteri> musteriler = q.getResultList();
        try {
            oos = new ObjectOutputStream(new FileOutputStream(dosya));
            oos.writeObject(musteriler);
            JOptionPane.showMessageDialog(rootPane, "Bilgiler Dosyaya İşlendi!");
        } catch (IOException ex) {
            Logger.getLogger(YoneticiEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            oos.close();
        } catch (IOException ex) {
            Logger.getLogger(YoneticiEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dosyayaatActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton dosyayaat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox_onay1;
    private javax.swing.JComboBox<Object> jComboBoxmusteriid;
    private javax.swing.JComboBox<String> jComboCihazDurumu;
    private javax.swing.JComboBox<String> jComboCihazTuru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtn_musteriEkle;
    private javax.swing.JButton jbtn_musteriSil;
    private javax.swing.JTable jtablemusterilistesi;
    private javax.swing.JTable jtableurunlistesi;
    private javax.swing.JTextField jtxt_TeslimTarihi;
    private javax.swing.JTextField jtxt_Ucret;
    private javax.swing.JTextField jtxt_musteriAdi;
    private javax.swing.JTextField jtxt_musteriSoyadi;
    // End of variables declaration//GEN-END:variables
}
