/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_1521221051_feyzanursaka_odev2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author Feyza Nur Saka
 */
public class YoneticiGirisEkrani extends javax.swing.JFrame {

    public static Yonetici y_logined;
    public static Musteri m_logined;

    /**
     * Creates new form YoneticiGirisEkrani
     */
    public YoneticiGirisEkrani() {
        initComponents();
        jBtn_Giris.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jBtn_Giris = new javax.swing.JButton();
        jbtn_yoneticiKayit = new javax.swing.JButton();
        jtxt_kullaniciAdi = new javax.swing.JTextField();
        jPassword_sifre = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jCheckBox_onay1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Kullanıcı Parolası :");

        jBtn_Giris.setText("Giriş");
        jBtn_Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_GirisActionPerformed(evt);
            }
        });

        jbtn_yoneticiKayit.setText("Yönetici Kayıt");
        jbtn_yoneticiKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_yoneticiKayitActionPerformed(evt);
            }
        });

        jLabel2.setText("Kullanıcı Adı        :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("        YÖNETİCİ GİRİŞ");

        jButton2.setText("<-- GERİ ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox_onay1.setText("Bilgileri Eksiksiz Doldurdum");
        jCheckBox_onay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_onay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 343, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_onay1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbtn_yoneticiKayit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(jBtn_Giris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxt_kullaniciAdi)
                                .addComponent(jPassword_sifre, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(jCheckBox_onay1)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Giris, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_yoneticiKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_GirisActionPerformed
  
            // TODO add your handling code here:

            Yonetici girisYapanYonetici = null;
 
            String kullaniciadi = jtxt_kullaniciAdi.getText();
            String sifre = String.copyValueOf(jPassword_sifre.getPassword());

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221051_FeyzaNurSAKA_Odev2PU");
        EntityManager em = emf.createEntityManager();
         Query q1 = em.createQuery("SELECT y FROM Yonetici y WHERE y.yoneticikullaniciadi=:y_kId AND y.yoneticisifre=:y_sif ");
        q1.setParameter("y_kId", kullaniciadi);
        q1.setParameter("y_sif", sifre);

   try {
            girisYapanYonetici = (Yonetici) q1.getSingleResult();
        } catch (Exception e) {
            girisYapanYonetici = null;
        }
     if (girisYapanYonetici != null) {
            y_logined = girisYapanYonetici;
            YoneticiEkrani newyoneticiekrani = new YoneticiEkrani();
            newyoneticiekrani.setVisible(true);
            this.dispose();
        
//            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
//            String sql = ("SELECT * FROM YONETICI WHERE YONETICIKULLANICIADI='" + jtxt_kullaniciAdi.getText() + "'");
//            PreparedStatement prStm = con.prepareStatement(sql);
//
//            ResultSet rs = prStm.executeQuery();
//            boolean b = true;
//            while (rs.next()) {
//                if (jtxt_kullaniciAdi.getText().equals(rs.getObject(4))
//                        && jPassword_sifre.getText().equals(rs.getObject(5))) {
//
//
//                    YoneticiEkrani yonetici = new YoneticiEkrani();
//                    yonetici.setVisible(true);
//                    b = false;
//                    this.dispose();
//                }
//            }
//            if (b) {
//                JOptionPane.showMessageDialog(rootPane, "Kullanici Adi ya da Şifre Geçersiz! ");
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(YoneticiGirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
//
//        }
     }
    }//GEN-LAST:event_jBtn_GirisActionPerformed

    private void jbtn_yoneticiKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_yoneticiKayitActionPerformed
        // TODO add your handling code here:
        YoneticiKayitEkrani newmusterikayitekrani = new YoneticiKayitEkrani();
        newmusterikayitekrani.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_yoneticiKayitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GirisEkrani newyoneticigirisekrani = new GirisEkrani();
        newyoneticigirisekrani.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox_onay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_onay1ActionPerformed
        // TODO add your handling code here:

        if (jCheckBox_onay1.isSelected()) {
            if (jtxt_kullaniciAdi.getText().length() == 0 || jPassword_sifre.getText().length() == 0) {
                jBtn_Giris.setEnabled(false);
                JOptionPane.showMessageDialog(rootPane, "Boş alan bırakmayın!");
                jCheckBox_onay1.setSelected(false);
            } else {
                jBtn_Giris.setEnabled(true);
            }
        } else {
            jBtn_Giris.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox_onay1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiGirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiGirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiGirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiGirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiGirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Giris;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox_onay1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassword_sifre;
    private javax.swing.JButton jbtn_yoneticiKayit;
    private javax.swing.JTextField jtxt_kullaniciAdi;
    // End of variables declaration//GEN-END:variables
}
